FROM uber/horovod:0.15.0-tf1.11.0-torch0.4.1-py3.5

# Create a working directory
RUN mkdir -p /app/code
WORKDIR "/app/code"

# Install dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
  rsync \
  sudo

# Install other python dependencies
RUN pip install \
  six lmdb tqdm click numpy pillow tensorboardX scipy opencv-python

# Create a non-root user and switch to it
RUN adduser --disabled-password --gecos '' --shell /bin/bash user \
 && chown -R user:user /app
RUN echo "user ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/90-user
USER user

# All users can use /home/user as their home directory
ENV HOME=/home/user
RUN chmod 777 /home/user

# Set the default command to python3
CMD ["python"]
